export * from './authData.interface';
export * from './side-bar-list.interface';
export * from './work.interface';
export * from './institution.interface';
export * from './cource.interface';
export * from './link.interface';
export * from './summary.interface';
export * from './side-bar.interface';
export * from './auth.interface';
